version = 3.7.17
align.preset = more
maxColumn = 80
runner.dialect = scala3
indent.defnSite = 2
indent.main = 2
rewrite.rules = [PreferCurlyFors]
#rewrite.scala3.convertToNewSyntax = yes
rewrite.scala3.removeOptionalBraces = yes
verticalMultiline.atDefnSite = true
#verticalMultiline.arityThreshold = 2 // .parMapN { (_, _) => }
verticalMultiline.newlineAfterOpenParen = true
newlines.implicitParamListModifierForce = [after]
includeCurlyBraceInSelectChains = true
includeNoParensInSelectChains = false
