version = 3.7.17
align.preset = more
maxColumn = 80
runner.dialect = scala3
indent.defnSite = 2
indent.main = 2
rewrite.rules = [PreferCurlyFors]
rewrite.preferCurlyFors.removeTrailingSemicolonsOnly=false
#rewrite.scala3.convertToNewSyntax = yes
rewrite.scala3.removeOptionalBraces = yes
rewrite.insertBraces.minLines = 1
rewrite.insertBraces.allBlocks = true
#newlines.source = unfold
verticalMultiline.atDefnSite = true
verticalMultiline.newlineAfterOpenParen = true
newlines.implicitParamListModifierForce = [after]
includeCurlyBraceInSelectChains = true
includeNoParensInSelectChains = false
